export { default as BankIcon } from '../../public/svg/BankIcon.svg'
export { default as UserIcon } from '../../public/svg/UserIcon.svg'
export { default as Bell } from '../../public/svg/Bell.svg'
export { default as BurgerIcon } from '../../public/svg/BurgerIcon.svg'
export { default as PhoneIcon } from '../../public/svg/PhoneIcon.svg'
export { default as EmailIcon } from '../../public/svg/EmailIcon.svg'
export { default as FbIcon } from '../../public/svg/FbIcon.svg'
export { default as InstagramIcon } from '../../public/svg/InstagramIcon.svg'
export { default as WhatsappIcon } from '../../public/svg/WhatsappIcon.svg'
export { default as LinkedinIcon } from '../../public/svg/LinkedinIcon.svg'
export { default as RateStar } from '../../public/svg/RateStar.svg'
export { default as RateStars } from '../../public/svg/RateStars.svg'

