export { default as BankIcon } from '../../public/svg/BankIcon.svg'
export { default as UserIcon } from '../../public/svg/UserIcon.svg'
export { default as Bell } from '../../public/svg/Bell.svg'
export { default as BurgerIcon } from '../../public/svg/BurgerIcon.svg'
export { default as PhoneIcon } from '../../public/svg/PhoneIcon.svg'
export { default as EmailIcon } from '../../public/svg/EmailIcon.svg'
